/* ------------------------------------------------------------------ *
 *  data.js — branches, links and site copy
 *
 *  This is the only file you need to touch for routine content edits.
 *  Menu artwork is listed in js/menu-pages.js, which is generated by
 *  tools/build-menus.py.
 * ------------------------------------------------------------------ */
(function (global) {
  'use strict';

  const SITE = {
    kicker: 'Coffee Roasters',
    /* the booklet cover poem, word for word */
    poem: [
      'your dose of happiness, your dose of love',
      'your tender song, of a morning dove',
      'your side of a story, upon the side you chose',
      'your daily dose',
    ],
    about:
      'What started as a cozy corner in El Gouna back in 2022 has grown into ' +
      'more than just a coffee spot—it’s your daily escape. Where specialty ' +
      'coffee, good vibes, and all-day brunch come together.',
    signoff: ['Roasted in house, always.', 'See you tomorrow?'],
  };

  const LINKS = {
    instagram: 'https://www.instagram.com/dailydose.coffeeroasters/',
    tiktok: 'https://www.tiktok.com/@dailydose.coffeeroasters',
    handle: '@dailydose.coffeeroasters',
    review:
      'https://docs.google.com/forms/d/e/1FAIpQLScNPdjoXoYfpfjdo7BmJKOJcpxxx2lvaYSniaaCE01zXpzXww/viewform?usp=header',
  };

  /* ---------------------------------------------------------------- *
   *  Branches
   *
   *  menu    which set of artwork this branch serves (key in MENU_PAGES)
   *  region  groups the cards on screen, nothing more. Kept broad on
   *          purpose so no branch is filed under a district it isn't in.
   * ---------------------------------------------------------------- */
  const BRANCHES = [
    { id: 'gouna',    name: 'Abu Tig Marina', region: 'El Gouna', menu: 'gouna',
      maps: 'https://maps.app.goo.gl/qZ8e1FSmnMoZ8xxM9' },
    { id: 'mivida',   name: 'Mivida',         region: 'Cairo',    menu: 'cairo',
      maps: 'https://maps.app.goo.gl/QeWSwuphXJHVDeLS9' },
    { id: 'majarrah', name: 'Majarrah',       region: 'Cairo',    menu: 'cairo',
      maps: 'https://maps.app.goo.gl/Kz8LY2wveZD8bwmq6' },
    { id: 'driive',   name: 'The Driive',     region: 'Cairo',    menu: 'kiosk',
      maps: 'https://maps.app.goo.gl/uTDzv42kKGwhGaCH8' },
    { id: 'owest',    name: 'O West',         region: 'Cairo',    menu: 'kiosk',
      maps: 'https://maps.app.goo.gl/LSo5REE3WjPdb9Bv6' },
  ];

  const REGION_ORDER = ['El Gouna', 'Cairo'];

  global.SITE = SITE;
  global.LINKS = LINKS;
  global.BRANCHES = BRANCHES;
  global.REGION_ORDER = REGION_ORDER;
})(window);
