/* ------------------------------------------------------------------ *
 *  data.js — branches, links and site copy
 *
 *  This is the only file you need to touch for routine content edits.
 *  Menu artwork is listed in js/menu-pages.js, which is generated by
 *  tools/build-menus.py.
 * ------------------------------------------------------------------ */
(function (global) {
  'use strict';

  const SITE = {
    kicker: 'Coffee Roasters',
    /* the booklet cover poem, word for word */
    poem: [
      'your dose of happiness, your dose of love',
      'your tender song, of a morning dove',
      'your side of a story, upon the side you chose',
      'your daily dose',
    ],
    about:
      'What started as a cozy corner in El Gouna back in 2022 has grown into ' +
      'more than just a coffee spot—it’s your daily escape. Where specialty ' +
      'coffee, good vibes, and all-day brunch come together.',
    signoff: ['Roasted in house, always.', 'See you tomorrow?'],
  };

  const LINKS = {
    instagram: 'https://www.instagram.com/dailydose.coffeeroasters/',
    tiktok: 'https://www.tiktok.com/@dailydose.coffeeroasters',
    handle: '@dailydose.coffeeroasters',
    review:
      'https://docs.google.com/forms/d/e/1FAIpQLScNPdjoXoYfpfjdo7BmJKOJcpxxx2lvaYSniaaCE01zXpzXww/viewform?usp=header',
  };

  /* ---------------------------------------------------------------- *
   *  Branches — one flat list, shown in this order.
   *
   *  menu  which set of artwork the branch serves (key in MENU_PAGES)
   *  maps  Google Maps link. Omit it and the card shows "Location soon"
   *        instead of a directions button.
   * ---------------------------------------------------------------- */
  const BRANCHES = [
    { id: 'gouna',    name: 'Abu Tig Marina',  place: 'El Gouna',      menu: 'gouna',
      maps: 'https://maps.app.goo.gl/qZ8e1FSmnMoZ8xxM9' },
    { id: 'mivida',   name: 'Mivida',          place: 'New Cairo',     menu: 'cairo',
      maps: 'https://maps.app.goo.gl/QeWSwuphXJHVDeLS9' },
    { id: 'driive',   name: 'The Driive',      place: '',              menu: 'kiosk',
      maps: 'https://maps.app.goo.gl/uTDzv42kKGwhGaCH8' },
    { id: 'owest',    name: 'O West',          place: '',              menu: 'kiosk',
      maps: 'https://maps.app.goo.gl/LSo5REE3WjPdb9Bv6' },
    { id: 'lavista',  name: 'La Vista',        place: 'Sahel',         menu: 'lavista',
      maps: 'https://maps.app.goo.gl/9W58a8pvPcG6a87GA' },
    { id: 'playa',    name: 'Playa',           place: 'Sahel',         menu: 'playa',
      maps: 'https://maps.app.goo.gl/zfbdD4a1FnQAdwSm7' },
    /* Mountain View: maps link still to come. */
    { id: 'mountain', name: 'Mountain View',   place: 'Sahel',         menu: 'mountain' },
  ];

  global.SITE = SITE;
  global.LINKS = LINKS;
  global.BRANCHES = BRANCHES;
})(window);
