/* Generated by tools/build-menus.py — do not edit by hand.
   Page images are rendered from the source booklets at their
   native aspect ratio. Re-run the script when a menu changes. */
window.MENU_PAGES = {
  "gouna": {
    "pages": [
      {
        "src": "assets/menus/gouna/p01.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p02.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p03.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p04.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p05.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p06.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p07.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p08.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p09.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p10.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p11.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p12.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p13.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p14.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p15.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p16.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p17.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p18.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p19.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p20.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p21.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p22.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p23.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p24.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/gouna/p25.webp",
        "w": 827,
        "h": 1746
      }
    ],
    "pdf": "assets/menus/DD-Gouna-Menu.pdf"
  },
  "cairo": {
    "pages": [
      {
        "src": "assets/menus/cairo/p01.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p02.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p03.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p04.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p05.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p06.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p07.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p08.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p09.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p10.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p11.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p12.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p13.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p14.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p15.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p16.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p17.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p18.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p19.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p20.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p21.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p22.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p23.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p24.webp",
        "w": 827,
        "h": 1746
      },
      {
        "src": "assets/menus/cairo/p25.webp",
        "w": 827,
        "h": 1746
      }
    ],
    "pdf": "assets/menus/DD-Cairo-Menu.pdf"
  },
  "kiosk": {
    "pages": [
      {
        "src": "assets/menus/kiosk/p01.webp",
        "w": 950,
        "h": 1050
      }
    ],
    "pdf": "assets/menus/DD-Driive-OWest-Menu.jpeg"
  },
  "lavista": {
    "pages": [
      {
        "src": "assets/menus/lavista/p01.webp",
        "w": 2835,
        "h": 1754
      },
      {
        "src": "assets/menus/lavista/p02.webp",
        "w": 2835,
        "h": 1754
      }
    ],
    "pdf": "assets/menus/DD-LaVista-Menu.pdf"
  },
  "playa": {
    "pages": [
      {
        "src": "assets/menus/playa/p01.webp",
        "w": 2658,
        "h": 1754
      },
      {
        "src": "assets/menus/playa/p02.webp",
        "w": 2658,
        "h": 1754
      }
    ],
    "pdf": "assets/menus/DD-Playa-Menu.pdf"
  },
  "mountain": {
    "pages": [
      {
        "src": "assets/menus/mountain/p01.webp",
        "w": 2658,
        "h": 1754
      },
      {
        "src": "assets/menus/mountain/p02.webp",
        "w": 2658,
        "h": 1754
      }
    ],
    "pdf": "assets/menus/DD-MountainView-Menu.pdf"
  }
};
