#!/usr/bin/env python3
"""
Rebuild the menu assets from the source artwork.

The site shows each menu exactly as designed — the booklet pages are
rendered straight to images at their native aspect ratio, nothing is
retyped or re-laid-out. Run this whenever a menu changes.

    pip install pymupdf pillow
    python tools/build-menus.py

Inputs (edit SOURCES below if the filenames change)
    DD Gouna Booklet (Gouna branch).pdf                 -> Abu Tig Marina
    DD Cairo Booklet (Mivida and Majarrah branches).pdf  -> Mivida, Majarrah
    DD Menu (The Drive and O West branches).jpeg         -> The Driive, O West

Outputs
    assets/menus/<key>/pNN.webp   one image per page
    assets/menus/<original>       the untouched file, for the download link
    js/menu-pages.js              page list + pixel dimensions
"""

import json
import os
import shutil
import sys

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit('Missing dependency: pip install pymupdf')
try:
    from PIL import Image
except ImportError:
    sys.exit('Missing dependency: pip install pillow')

# --- configuration --------------------------------------------------
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.environ.get('DD_MENU_SRC', os.path.expanduser('~/Downloads/DD menus'))
OUT_DIR = os.path.join(HERE, 'assets', 'menus')

DPI = 150        # 827x1746 px for a 5.5x11.6in page — crisp on retina
QUALITY = 80

SOURCES = [
    # key,    source filename,                                        download name
    ('gouna', 'DD Gouna Booklet (Gouna branch).pdf',                  'DD-Gouna-Menu.pdf'),
    ('cairo', 'DD Cairo Booklet (Mivida and Majarrah branches).pdf',  'DD-Cairo-Menu.pdf'),
    ('kiosk', 'DD Menu (The Drive and O West branches).jpeg',         'DD-Driive-OWest-Menu.jpeg'),
]


def render_pdf(key, path):
    doc = fitz.open(path)
    pages = []
    os.makedirs(os.path.join(OUT_DIR, key), exist_ok=True)
    for i, page in enumerate(doc):
        pix = page.get_pixmap(dpi=DPI)
        img = Image.frombytes('RGB', (pix.width, pix.height), pix.samples)
        rel = '%s/p%02d.webp' % (key, i + 1)
        img.save(os.path.join(OUT_DIR, rel), 'WEBP', quality=QUALITY, method=6)
        pages.append({'src': 'assets/menus/' + rel, 'w': img.width, 'h': img.height})
    return pages


def render_image(key, path):
    img = Image.open(path).convert('RGB')
    os.makedirs(os.path.join(OUT_DIR, key), exist_ok=True)
    rel = '%s/p01.webp' % key
    img.save(os.path.join(OUT_DIR, rel), 'WEBP', quality=84, method=6)
    return [{'src': 'assets/menus/' + rel, 'w': img.width, 'h': img.height}]


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    manifest = {}

    for key, filename, download in SOURCES:
        path = os.path.join(SRC_DIR, filename)
        if not os.path.exists(path):
            sys.exit('Not found: %s\n(set DD_MENU_SRC to the folder holding the menus)' % path)

        pages = (render_pdf if path.lower().endswith('.pdf') else render_image)(key, path)
        shutil.copy(path, os.path.join(OUT_DIR, download))
        manifest[key] = {'pages': pages, 'pdf': 'assets/menus/' + download}

        size = sum(
            os.path.getsize(os.path.join(HERE, p['src'].replace('/', os.sep)))
            for p in pages
        )
        print('%-6s %2d page(s)  %dx%d  %.2f MB'
              % (key, len(pages), pages[0]['w'], pages[0]['h'], size / 1e6))

    out = os.path.join(HERE, 'js', 'menu-pages.js')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('/* Generated by tools/build-menus.py — do not edit by hand.\n')
        fh.write('   Page images are rendered from the source booklets at their\n')
        fh.write('   native aspect ratio. Re-run the script when a menu changes. */\n')
        fh.write('window.MENU_PAGES = ' + json.dumps(manifest, indent=2) + ';\n')
    print('\nwrote', os.path.relpath(out, HERE))


if __name__ == '__main__':
    main()
